import Link from 'next/link'
import Image from 'next/image'
import { Button } from "@/components/ui/button"
import { ArrowRight } from 'lucide-react'

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white">
      {/* Hero Section 1: Main Introduction */}
      <section className="py-20 md:py-32">
        <div className="container mx-auto px-4">
          <div className="grid items-center gap-12 md:grid-cols-2">
            <div>
              <h1 className="mb-6 text-5xl font-extrabold tracking-tight sm:text-6xl md:text-7xl">
                Learn with AI
              </h1>
              <p className="mb-8 text-xl text-gray-600 sm:text-2xl">
                Unlock your potential with personalized AI-powered learning experiences tailored just for you.
              </p>
              <Button asChild size="lg" className="text-lg">
                <Link href="/login">Start Learning</Link>
              </Button>
            </div>
            <div className="relative h-64 w-full md:h-96">
              {/* Placeholder for Illustration 1 */}
              <div className="absolute inset-0 bg-blue-100 rounded-lg flex items-center justify-center text-blue-500">
                Illustration 1: AI Learning Concept
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Hero Section 2: AI-Curated Learning Plans */}
      <section className="bg-white py-20 md:py-32">
        <div className="container mx-auto px-4">
          <div className="grid items-center gap-12 md:grid-cols-2">
            <div className="order-2 md:order-1 relative h-64 w-full md:h-96">
              {/* Placeholder for Illustration 2 */}
              <div className="absolute inset-0 bg-green-100 rounded-lg flex items-center justify-center text-green-500">
                Illustration 2: Personalized Learning Path
              </div>
            </div>
            <div className="order-1 md:order-2">
              <h2 className="mb-6 text-4xl font-bold sm:text-5xl">
                AI-Curated Learning Plans
              </h2>
              <p className="mb-8 text-xl text-gray-600">
                Experience learning tailored to your goals, pace, and style. Our AI analyzes your needs and creates the perfect learning path for you.
              </p>
              <Button asChild variant="outline" size="lg" className="text-lg">
                <Link href="/login">
                  Create a Plan
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Hero Section 3: AI-Generated Personalized Content */}
      <section className="py-20 md:py-32">
        <div className="container mx-auto px-4">
          <div className="grid items-center gap-12 md:grid-cols-2">
            <div>
              <h2 className="mb-6 text-4xl font-bold sm:text-5xl">
                Personalized AI-Generated Content
              </h2>
              <p className="mb-8 text-xl text-gray-600">
                Experience tailored, cutting-edge content generated by AI. Our platform creates personalized materials that adapt to your learning style, interests, and progress.
              </p>
              <Button asChild variant="outline" size="lg" className="text-lg">
                <Link href="/login">
                  Explore Your Content
                  <ArrowRight className="ml-2 h-5 w-5" />
                </Link>
              </Button>
            </div>
            <div className="relative h-64 w-full md:h-96">
              {/* Placeholder for Illustration 3 */}
              <div className="absolute inset-0 bg-purple-100 rounded-lg flex items-center justify-center text-purple-500">
                Illustration 3: Personalized AI Content
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Hero Section 4: AI-Curated Adaptive Quizzes and Tests */}
      <section className="bg-white py-20 md:py-32 text-black">
        <div className="container mx-auto px-4">
          <div className="grid items-center gap-12 md:grid-cols-2">
        <div className="order-2 md:order-1">
          <h2 className="mb-6 text-4xl font-bold sm:text-5xl">
            AI-Curated Adaptive Quizzes & Tests
          </h2>
          <p className="mb-8 text-xl text-gray-600">
            Reinforce your knowledge with AI-curated and conducted assessments that adapt to your progress. Our intelligent system identifies areas for improvement and personalizes each quiz to maximize your learning.
          </p>
          <Button asChild variant="secondary" size="lg" className="text-lg">
            <Link href="/login">
          Try an AI Quiz Now
          <ArrowRight className="ml-2 h-5 w-5" />
            </Link>
          </Button>
        </div>
        <div className="order-1 md:order-2 text-center">
          <div className="inline-flex items-center justify-center rounded-full bg-black p-3">
            <svg
          className="h-16 w-16 text-white"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          strokeWidth="2"
            >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
          />
            </svg>
          </div>
          <p className="mt-4 text-lg font-semibold">Boost Your Learning</p>
          <p className="mt-2 text-sm text-gray-600">
            Our AI-curated adaptive quizzes help you learn faster and more effectively
          </p>
        </div>
          </div>
        </div>
      </section>
    </div>
  )
}

